# input
project_id: 42201
use_cache: False
task_type: "Object detection"
# model
arch_type: "DINO"
model_source: "Pretrained models"
model_name: "dino-4scale_r50_8xb2-12e_coco.py"
train_mode: "finetune"
# hyperparameters
# general
n_epochs: 20
input_image_size: [1000, 600]
train_batch_size: 2
val_batch_size: 1
val_interval: 1
chart_interval: 1
# checkpoint
checkpoint_interval: 1
keep_checkpoints: True
max_keep_checkpoints: 3
save_last_checkpoint: True
save_best_checkpoint: True
save_optimizer_state: False
# optimizer
override_frozen_stages: False
optimizer: "AdamW"
lr: 0.0001
weight_decay: 0.0001
use_clip_grad_norm: True
clip_grad_norm: 0.1
use_amsgrad: True
beta1: 2342
beta2: 123
sgd_momentum: 44
# lr scheduler
scheduler: "empty"
use_warmup: True
warmup_iters: 1
warmup_ratio: 0.001
model_evaluation_bm: True
